apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  # type: NodePort
  type: ClusterIP
  ports:
  - name: "result-service"
    port: 80
    targetPort: 80
    # nodePort: 31001
  selector:
    app: result
